### ISSUE TITLE
AginahBot doesn't work with PST/PDT

### ISSUE THREAD

**Issue by zig-for** [LegendaryLinux/AginahBot#2]
Because of https://github.com/moment/moment-timezone/issues/249

Possible solutions - 

1. Add the timezone manually as suggested in the issue report
2. Change the regex to allow stuff like `PST8PDT`, `America/Los_Angeles`, `US/Pacific`
3. Just use moment's built in time parser ( https://jsfiddle.net/6Lh2czvo/ )

**Comment by zig-for** [comment]
To be clear, I'm happy to implement any or all of these solutions, but you gotta tell me which you want as it's not my codebase.

**Comment by LegendaryLinux** [comment]
Thank you for the report. I've been aware of this issue for some time, but was under the impression only the CST timezone was missing. Since this seems to be a bit more problematic, I'll give this some priority.

Part of the reason I parse explicitly for timezone abbreviations is because most people aren't familiar with `America/Los_Angeles` style timezones. Using moment's built in parser requires that people know how to enter datetime values in a way the moment library supports, so that will fail on occasion.

Adding the timezone abbreviation manually is a decent workaround, but my ideal solution is to build something from scratch. I'm envisioning a custom JSON file which contains abbreviations and hour offsets. Using this, I can actually use the native `Date` function in conjunction with strict ISO-8601 datetime strings (e.g. `2020-01-01T12:00:00+03:00`) to force a correct time integer. This solution has the side-effect of no longer requiring `moment-timezone`.

I'll try to get a solution to this issue worked out tonight.

**Comment by LegendaryLinux** [comment]
Because there are so many duplicate zone abbreviations, the best course of action was to take @zig-for's suggestion #2 and allow the user to enter more varied zone information. The updated regexes did not impact the parsing functions, which was nice.

Because most users will not be familiar with the `America/Los_Angeles` notation for zones, I have included a wikipedia link in the `!aginah help schedule` command. It's not the solution I want, but it's the best I have. This patch is love now.

It's worth noting the _ideal_ solution is for Discord to collect timezone information for users, at the user's discretion. This could then be made available through the API to support international communities.
